apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storm-oci-demo
  namespace: storm-oci-demo
spec:
  interval: 10m
  targetNamespace: storm-oci-demo
  sourceRef:
    kind: OCIRepository
    name: storm-oci-demo
  prune: true
  timeout: 1m